//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERI
    {
        public MUSTERI()
        {
            this.REZERVASYON = new HashSet<REZERVASYON>();
        }
    
        public decimal ID { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public decimal ILID { get; set; }
        public string POSTAKODU { get; set; }
        public string EMAIL { get; set; }
        public string TELEFON { get; set; }
        public string FAKS { get; set; }
    
        public virtual IL IL { get; set; }
        public virtual ICollection<REZERVASYON> REZERVASYON { get; set; }
    }
}
