//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODA
    {
        public decimal ID { get; set; }
        public decimal ODAKAPASITEID { get; set; }
        public decimal ODATIPID { get; set; }
    
        public virtual ODAKAPASITE ODAKAPASITE { get; set; }
        public virtual ODATIPI ODATIPI { get; set; }
    }
}
