//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODAKAPASITE
    {
        public ODAKAPASITE()
        {
            this.ODA = new HashSet<ODA>();
        }
    
        public decimal ID { get; set; }
        public string ADI { get; set; }
        public string SAYISI { get; set; }
        public Nullable<decimal> ODATIPID { get; set; }
    
        public virtual ICollection<ODA> ODA { get; set; }
        public virtual ODATIPI ODATIPI { get; set; }
    }
}
