//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODATIPI
    {
        public ODATIPI()
        {
            this.ODA = new HashSet<ODA>();
            this.ODAKAPASITE = new HashSet<ODAKAPASITE>();
            this.REZERVASYON = new HashSet<REZERVASYON>();
        }
    
        public decimal ID { get; set; }
        public string ADI { get; set; }
        public string RESIMI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual ICollection<ODA> ODA { get; set; }
        public virtual ICollection<ODAKAPASITE> ODAKAPASITE { get; set; }
        public virtual ICollection<REZERVASYON> REZERVASYON { get; set; }
    }
}
