//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODEMETIPI
    {
        public ODEMETIPI()
        {
            this.REZERVASYON = new HashSet<REZERVASYON>();
        }
    
        public decimal ID { get; set; }
        public string ODEMEADI { get; set; }
    
        public virtual ICollection<REZERVASYON> REZERVASYON { get; set; }
    }
}
