//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IL> IL { get; set; }
        public DbSet<MUSTERI> MUSTERI { get; set; }
        public DbSet<ODA> ODA { get; set; }
        public DbSet<ODAKAPASITE> ODAKAPASITE { get; set; }
        public DbSet<ODATIPI> ODATIPI { get; set; }
        public DbSet<ODEMETIPI> ODEMETIPI { get; set; }
        public DbSet<OTEL> OTEL { get; set; }
        public DbSet<REZERVASYON> REZERVASYON { get; set; }
        public DbSet<REZERVASYONDURUM> REZERVASYONDURUM { get; set; }
        public DbSet<ULKE> ULKE { get; set; }
        public DbSet<YONETICI> YONETICI { get; set; }
    
        public virtual int ADD_ODEME_TIPI(Nullable<decimal> p_ODEMETIP_ID, string p_ODEMEADI)
        {
            var p_ODEMETIP_IDParameter = p_ODEMETIP_ID.HasValue ?
                new ObjectParameter("P_ODEMETIP_ID", p_ODEMETIP_ID) :
                new ObjectParameter("P_ODEMETIP_ID", typeof(decimal));
    
            var p_ODEMEADIParameter = p_ODEMEADI != null ?
                new ObjectParameter("P_ODEMEADI", p_ODEMEADI) :
                new ObjectParameter("P_ODEMEADI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_ODEME_TIPI", p_ODEMETIP_IDParameter, p_ODEMEADIParameter);
        }
    
        public virtual int RAISE_ODA_FIYAT(Nullable<decimal> p_ID, Nullable<decimal> p_PERCENT)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(decimal));
    
            var p_PERCENTParameter = p_PERCENT.HasValue ?
                new ObjectParameter("P_PERCENT", p_PERCENT) :
                new ObjectParameter("P_PERCENT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RAISE_ODA_FIYAT", p_IDParameter, p_PERCENTParameter);
        }
    }
}
